name: My First Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command
        run: echo "pipeline is running"

      - name: Show files
        run: ls

- name: Build Docker image
        run: docker build -t mous .
